server:
  port: 8002

spring:
  datasource:
#    对Driver自定义，实现分库分表等隐藏逻辑
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
#    ShardingSphere配置文件路径
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
  data:
    redis:
      host: 127.0.0.1
      port: 6379